# Generated by Django 5.2.7 on 2025-10-27 06:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text Input'), ('select', 'Dropdown Selection'), ('checkbox', 'Checkboxes')], max_length=20, verbose_name='field type'),
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='process title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('process_type', models.CharField(choices=[('linear', 'Linear Process'), ('free', 'Free Process')], max_length=10, verbose_name='process type')),
                ('is_public', models.BooleanField(default=True, verbose_name='public')),
                ('access_password', models.CharField(blank=True, max_length=255, null=True, verbose_name='access password')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
            options={
                'verbose_name': 'process',
                'verbose_name_plural': 'processes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_name', models.CharField(max_length=255, verbose_name='step name')),
                ('step_description', models.TextField(blank=True, verbose_name='step description')),
                ('order_num', models.PositiveIntegerField(default=0, verbose_name='order number')),
                ('is_required', models.BooleanField(default=True, verbose_name='required')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.form', verbose_name='form')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_steps', to='forms.process')),
            ],
            options={
                'verbose_name': 'process step',
                'verbose_name_plural': 'process steps',
                'ordering': ['order_num', 'created_at'],
                'unique_together': {('process', 'order_num')},
            },
        ),
    ]
