# Generated by Django 5.2.7 on 2025-10-31 09:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('form', 'type', 'created_by'), name='uniq_report_per_user_form_type'),
        ),
    ]
