# Generated by Django 5.2.7 on 2025-10-27 07:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_alter_field_field_type_process_processstep'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='entitycategory',
            options={'ordering': ['-created_at'], 'verbose_name': 'entity category', 'verbose_name_plural': 'entity categories'},
        ),
        migrations.AlterModelOptions(
            name='formview',
            options={'ordering': ['-viewed_at'], 'verbose_name': 'form view', 'verbose_name_plural': 'form views'},
        ),
        migrations.AddField(
            model_name='processstep',
            name='is_mandatory',
            field=models.BooleanField(default=True, verbose_name='mandatory'),
        ),
        migrations.AlterUniqueTogether(
            name='entitycategory',
            unique_together={('entity_type', 'entity_id', 'category')},
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='forms.form')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='submitted by')),
            ],
            options={
                'verbose_name': 'response',
                'verbose_name_plural': 'responses',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.TextField(verbose_name='answer value')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.field', verbose_name='field')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='forms.response')),
            ],
            options={
                'verbose_name': 'answer',
                'verbose_name_plural': 'answers',
                'ordering': ['field__order_num', 'created_at'],
                'unique_together': {('response', 'field')},
            },
        ),
    ]
