# Generated by Django 5.2.7 on 2025-10-28 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_alter_category_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='formview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='formview',
            name='ip_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='formview',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('summary', 'Summary'), ('realtime', 'Realtime'), ('api', 'API')], max_length=20)),
                ('data_config', models.JSONField(blank=True, default=dict)),
                ('schedule_type', models.CharField(choices=[('manual', 'Manual'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='manual', max_length=20)),
                ('delivery_method', models.CharField(choices=[('email', 'Email'), ('api', 'API')], default='email', max_length=20)),
                ('target_endpoint', models.CharField(blank=True, max_length=512, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='forms.form')),
            ],
            options={
                'verbose_name': 'report',
                'verbose_name_plural': 'reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
