# Generated by Django 5.2.7 on 2025-10-28 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_formview_user_alter_formview_ip_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processstep',
            name='is_required',
        ),
    ]
